/** Greeting lines shown in a new character's speech bubble the moment they
 * join the back of the counter line (see CharacterQueue's `entering` state).
 * Purely decorative flavor text — not tied to game state. */
export const SPEECH_PHRASES = [
  "Hello! I'd like a coffee, please.",
  'Good morning! One coffee, please.',
  'Coffee time! Can I get one, please?',
  "Hi there! I'd love a coffee.",
  'One coffee for me, please!',
  'Morning! Coffee, please?',
  'Hello! Could I have a coffee?',
  'Hi! I need my coffee fix.',
  "Coffee, please — I'm in a hurry!",
  "Good day! One coffee, if you don't mind.",
  'Hiya! A coffee would be great.',
  "I'll have a coffee, thank you!",
  'Can I get a coffee, please?',
  'Hello! Coffee for me, please.',
  "Hi! I'm here for my coffee.",
  'Coffee, please — extra warm!',
  'Good afternoon! Coffee, please.',
  "Hey! I'd really like a coffee.",
  'Hello there! Just a coffee, please.',
  'Morning! Could I get a coffee?',
  'Hi! A cup of coffee, please.',
  "I could really use a coffee right now.",
  'Hello! One coffee for me, thanks.',
  'Hey there! Coffee, please?',
  'Good morning! Coffee time for me.',
  "Hi! I'm ready for my coffee.",
  'Could I please have a coffee?',
  'Hello! Just a small coffee, please.',
  'Hi there! One coffee, please.',
  'Coffee please — I just woke up!',
  'Good day! Coffee for me, please.',
  "Hello! I'm craving a coffee.",
  'Hi! Coffee, please, when you can.',
  'One coffee, please — thank you!',
  'Hey! Can I grab a coffee?',
  'Morning! One coffee for me, please.',
  'Hi there! Coffee would be lovely.',
  "Hello! I'll take a coffee, please.",
  'Coffee, please — I have a big day!',
  'Hi! Could I get a coffee, please?',
  "Good morning! I'd like a coffee.",
  'Hey there! A coffee, please.',
  'Hello! One coffee, please and thanks.',
  'Hi! Coffee time — for me, please.',
  "I'd love a coffee, please!",
  'Good afternoon! One coffee, please.',
  'Hello! Coffee for me — please and thank you.',
  'Hi there! Just one coffee, please.',
  'Morning! A coffee would be wonderful.',
  'Hello! Coffee, please — I appreciate it!',
] as const

export type SpeechPhrase = (typeof SPEECH_PHRASES)[number]
